### ISSUE TITLE
Add language command

### ISSUE THREAD

**Issue by Anubhav1603** [wpmjones/apibot#1]
I would love to see command added like !python, !js, etc. for new comers who join our awsome server how to get started and all.

### Do you want to work on this issue:
- [x] Like to work on this issue myself
- [ ] Anyone can add this feature

**Comment by wpmjones** [comment]
Sounds good.  I would recommend doing a PR and send it over and I'd be happy to add these.  Just do your best to follow the "Shared development tips" at the top of bot.py.  general.py would probably be the best place to add these commands.  Thanks!
